apiVersion: v1
kind: Service
metadata:
  name: mysql-svc
  labels:
    k8s-app: mysql
spec:
  type: NodePort
  ports:
    - port: 3306
      nodePort: 30020
  selector:
    k8s-app: mysql
