apiVersion: v1
kind: Service
metadata:
  name: ghost-svc
  labels:
    k8s-app: ghost
spec:
  type: NodePort
  ports:
    - port: 2368
      nodePort: 30030
  selector:
    k8s-app: ghost
