apiVersion: v1
kind: Service
metadata:
  name: minio-svc
spec:
  type: NodePort
  ports:
    - port: 9000
      targetPort: 9000
      protocol: TCP
      nodePort: 30010
  selector:
    k8s-app: minio
